### ISSUE TITLE
Auth with supabase can be simplier :)

### ISSUE THREAD

**Issue by guillaumeduhan** [AdelDima/youtube-to-notion#1]
Hello @AdelDima,

Just saw your auth:

https://github.com/AdelDima/youtube-to-notion/blob/6952326e875c6d6da1a3ca17105f49c13411297d/pages/index.tsx#L64

You can do something simplier like:

https://github.com/guillaumeduhan/supabase-nextjs/blob/main/pages/index.js

Enjoy :)

**Comment by AdelDima** [comment]
@guillaumeduhan  thanks a lot, I'll check it out, I used local storage to stop requests to superbase each time the user changed the browser tab or refreshed the page.  

:)

**Comment by guillaumeduhan** [comment]
enjoy my friend :)
