### ISSUE TITLE
Importing Playlist issue - Error 500

### ISSUE THREAD

**Issue by alyahyaoui** [AdelDima/youtube-to-notion#2]
I have an issue with the integration
![image](https://github.com/AdelDima/youtube-to-notion/assets/59417071/a443d272-7252-4465-a07a-6d9e62998c42)

**Comment by AdelDima** [comment]
Hi,
have you tried updating Notion Token, and login again?  
![image](https://github.com/AdelDima/youtube-to-notion/assets/3769804/dd1c7a3d-9725-4860-a773-b73de076bbef)

please send me the play list I'll try it on my end.

**Comment by alyahyaoui** [comment]
yes i did 2 times

**Comment by AdelDima** [comment]
can you please give me your playlist URL and your database ID, just to make sure it's okay?

**Comment by alyahyaoui** [comment]
https://youtube.com/playlist?list=PLuJCSkbX9W56nhlV3pnvYJJilXyA0w-ka&si=VuuKIlwBIm_en3-T
f313b33978494db4b92f558a90978c30

**Comment by AdelDima** [comment]
> https://youtube.com/playlist?list=PLuJCSkbX9W56nhlV3pnvYJJilXyA0w-ka&si=VuuKIlwBIm_en3-T f313b33978494db4b92f558a90978c30

please use this link: https://www.youtube.com/watch?v=IrIAmq80VEE&list=PLuJCSkbX9W56nhlV3pnvYJJilXyA0w-ka

**Comment by cwagner22** [comment]
Same issue even using the playlist url mentioned

**Comment by aidosz** [comment]
Hi! I have the same issue even with using 2 types of youtube playlist links. Did you find any solution or this service is not working any more?  @AdelDima

**Comment by dmitriygoncharenko** [comment]
Same problem, seems no support anymore(
